program: main.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --overwrite
  - ${args_json}
name: batchsize sweep
metric:
  name: approx/L1
  goal: minimize
method: grid
parameters:
  batch_size:
    values:
      - 16
      - 128
      - 1024
      - 8192
      - 65536
      - 524288
