program: main.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --overwrite
  - ${args_json}
name: lr sweep
metric:
  name: approx/L1
  goal: minimize
method: grid
parameters:
  loss_mode:
    values:
      - "bsde_eff"
      - "fk"
      - "detach"
      - "model_eff"
  problem_kwargs.diffusivity:
    values:
      - 0.125
      - 0.5
      - 1.
      - 1.5
