program: main.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --overwrite
  - ${args_json}
name: mode sweep
metric:
  name: approx/L1
  goal: minimize
method: grid
parameters:
  loss_mode:
    values:
      - "bsde"
      - "model"
      - "bsde_eff"
      - "fk"
      - "detach"
      - "model_eff"
