program: main.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --overwrite
  - ${args_json}
name: scaling sweep
metric:
  name: approx/L1
  goal: minimize
method: grid
parameters:
  batch_size:
    values:
      - 1
      - 8
      - 64
      - 512
      - 4096
      - 32768
  loss_mode:
    values:
      - "fk"
      - "detach"